openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: wabli-community-51
  url: https://83.212.100.226:5001/v1
security:
- {}
tags:
- description: not yet ready
  name: welcomeentity
paths:
  /welcomeentity:
    post:
      operationId: createwelcomeentity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/welcomeentity'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcomeentity'
          description: successful operation
      summary: Creates the data
      tags:
      - welcomeentity
      x-eov-operation-handler: controllers/WelcomeentityController
  /welcomeentity/{welcomeentityId}:
    delete:
      operationId: deletewelcomeentity
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: welcomeentityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - welcomeentity
      x-eov-operation-handler: controllers/WelcomeentityController
    get:
      operationId: getwelcomeentity
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: welcomeentityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcomeentity'
          description: successful operation
      summary: Get the element
      tags:
      - welcomeentity
      x-eov-operation-handler: controllers/WelcomeentityController
    put:
      operationId: updatewelcomeentity
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: welcomeentityId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/welcomeentity'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcomeentity'
          description: successful operation
      summary: Updates the element
      tags:
      - welcomeentity
      x-eov-operation-handler: controllers/WelcomeentityController
  /welcomeentity/getAll:
    get:
      operationId: getAllwelcomeentity
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/welcomeentity'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - welcomeentity
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/WelcomeentityController
  /welcomeentity/getByParams:
    get:
      operationId: getByParamswelcomeentity
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/welcomeentity'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - welcomeentity
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/WelcomeentityController
components:
  schemas:
    welcomeentity:
      example:
        _id: _id
        title: title
      properties:
        _id:
          type: string
        title:
          type: string
      required:
      - title
      type: object
